name: Bundle Analysis

on:
  pull_request:
    branches: [ main, master ]
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.vue'
      - 'package.json'
      - 'nuxt.config.ts'

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.6.0'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Build with bundle analyzer
        run: |
          export ANALYZE=true
          npm run build
      
      - name: Save bundle stats
        uses: actions/upload-artifact@v3
        with:
          name: bundle-stats
          path: .nuxt/stats