name: Deploy to NuxtHub
on: push

jobs:
  deploy:
    name: "Deploy to NuxtHub"
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/master' && 'production' || 'preview' }}
      url: ${{ steps.deploy.outputs.deployment-url }}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install npm dependencies (creates node_modules)
        run: deno install

      - name: Prepare Nuxt (run nuxt prepare)
        run: deno run -A npm:nuxt prepare

      - name: Ensure NuxtHub module is installed
        run: deno run -A npm:nuxthub@latest ensure

      - name: Build application
        run: deno task build

      - name: Deploy to NuxtHub
        uses: nuxt-hub/action@v1
        id: deploy
        with:
          project-key: link-shortener-7f7h

