name: Security Checks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0' # Run once per week on Sunday at midnight

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
          
      - name: Run security checks
        run: deno task check
        continue-on-error: true  # Don't fail the workflow if issues are found
      
      - name: Audit dependencies
        run: deno audit
        continue-on-error: true  # Don't fail the workflow if vulnerabilities are found
      
      # Optional: Run more advanced security scans with tools like Snyk if needed
      # - name: Snyk vulnerability scan
      #   uses: snyk/actions/node@master
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   with:
      #     args: --severity-threshold=high